- name: Profile Readme Development Stats
  uses: anmol098/waka-readme-stats@V1.1
    with:
      # GitHub access token with Repo scope
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # Your Wakatime API Key
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
